export const auth = {

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT: 'LOGOUT',

    UPDATE_USER: 'UPDATE_USER',
    
    INVALID_REQUEST : 'INVALID_REQUEST'
};
