export const profileActions = {
    REQUEST_PROFILE : 'REQUEST_PROFILE',
    RECEIVE_PROFILE : 'RECEIVE_PROFILE',

    DISPLAY_TWEETS : 'TWEETS',
    DISPLAY_FOLLOWERS : 'FOLLOWERS',
    DISPLAY_LIKES : 'LIKES',
    DISPLAY_FOLLOWING : 'FOLLOWING',

    UPDATE_PROFILE : 'UPDATE_PROFILE_USER',
    RESET_DISPLAY : 'RESET_PROFILE_DISPLAY',

    PROFILE_ERROR : 'PROFILE_ERROR'
}
