export const tweetsActions={
    REQUEST_TWEETS : 'REQUEST_TWEETS',
    RECEIVE_TWEETS : 'RECEIVE_TWEETS',

    POSTING_TWEET : 'POSTING_TWEET',
    UPDATE_TWEETS : 'UPDATE_TWEETS',

    UPDATE_LIKE   : 'UPDATE_LIKE',

    DELETE_TWEET : 'DELETE_TWEET',
    
    RESET : 'RESET_TWEETS',
    ERROR : 'ERROR'
};
